/**
 * create-* skills — operator workflows.
 * Source: AGENT_KODY.systemPrompt § "Create issue / Create Kody agentResponsibility / Create Kody agent".
 */

import type { SkillEntry } from "./types";

export const DEFAULT_SKILL_CREATE_ISSUE: SkillEntry = {
  slug: "create-issue",
  title: "create-issue",
  body: `If \`## Current task\` is present and the user is asking to fix / change / continue **that** issue (not clearly separate work), do NOT call \`create_*\` / \`report_bug\` — that creates a duplicate issue. Treat the selected issue as the artifact: research, agree on missing scope, and suggest the issue text/comment the user should add. If the user asks to run or implement it, say it is ready to run from the issue workflow outside Kody chat. Only create a new issue if the request is unmistakably unrelated to the current task, and say so first.

Never call \`create_*\` / \`report_bug\` on first turn.

1. Research (3–5 tool calls).
2. Ask gap-closing questions in batches of 1–3. Loop until scope, acceptance criteria, and out-of-scope are explicit.
3. Show title + body once for approval, then call the matching tool:
   - bug → \`report_bug\` · new capability → \`create_feature\` · improvement → \`create_enhancement\` · restructure → \`create_refactor\` · docs → \`create_documentation\` · deps/config → \`create_chore\`.
4. \`additionalContext\` MUST end with **Research notes**: 2–4 bullets, file:line evidence ("no matches" is valid). Paths in \`affectedArea\` and symbols in \`requirements\` MUST come from tool results this session.`,
};

export const DEFAULT_SKILL_CREATE_DUTY: SkillEntry = {
  slug: "create-agentResponsibility",
  title: "create-agentResponsibility",
  body: `State-repo \`agent-responsibilities/<slug>/\` is recurring work: \`profile.json\` holds action/cadence/agent/agentAction metadata and \`agent-responsibility.md\` holds purpose, allowed commands, and restrictions. First call \`read_agent_responsibility_creation_guide\`. Never first turn.

Sufficiency: purpose, agent, schedule, allowed commands, restrictions, optional agentActions, and optional inputs. If the work should produce reports, select or create a report agentAction; do not put report settings or report paths in the agentResponsibility. Show the profile and body, then call \`create_or_update_agent_responsibility\` — the same tool handles both new agentResponsibilities and patches to an existing one (read-merge: omit a field to preserve it; pass \`body\` to replace the markdown; only call it after the user approves the diff).

**Key fields:** \`agent\` is the engine-aligned agentIdentity slug (the engine reads \`config.agent\`) \`agentActions\` (array) is for multi-run agentResponsibilities; \`agentAction\` (singular) is the convenience alias. Reports are generated by report agentActions; do not add report settings or report paths to agentResponsibility bodies. \`profile\` (raw object) overrides any profile.json field the typed schema doesn't expose — use it for engine-specific keys, not as a substitute for the typed fields.`,
};

export const DEFAULT_SKILL_CREATE_AGENT: SkillEntry = {
  slug: "create-agent",
  title: "create-agent",
  body: `State-repo \`agents/<slug>.md\` — a pure reusable identity file (markdown body: intent, allowed commands, restrictions). Agents have no schedule, no state, no run/tick; they're agent identities referenced by other flows. Same gap loop and sufficiency bar as Create Kody agentResponsibility. Show body, then call \`create_kody_agent\`.`,
};
