/**
 * @fileType module
 * @domain picker
 * @pattern message-protocol
 * @ai-summary Shared message contract + types between the dashboard and the
 *   Kody Element Picker browser extension. Mirrors extension/src/content.js.
 */

/** `window.postMessage` discriminators. Mirrored in extension/src/content.js. */
export const PICKER_PAGE_SOURCE = "kody-picker:page";
export const PICKER_EXT_SOURCE = "kody-picker:ext";

/** Static download for the unpacked extension (regenerated by `pnpm picker:pack`). */
export const PICKER_DOWNLOAD_PATH = "/kody-element-picker.zip";
/** User-facing install/setup guide. */
export const PICKER_DOCS_URL =
  "https://github.com/aharonyaircohen/Kody-Dashboard/blob/main/docs/element-picker.md";
/** One-line install hint shown on download (full steps in PICKER_DOCS_URL). */
export const PICKER_INSTALL_HINT =
  "Picker downloading. Unzip it, open chrome://extensions, turn on Developer mode, click Load unpacked, pick the folder, then reload this tab.";

/** A DOM element the user clicked inside the preview iframe. */
export interface PickedElement {
  /** Best-effort CSS selector (id-anchored, else nth-of-type path). */
  selector: string;
  tagName: string;
  id: string | null;
  classes: string[];
  /** Trimmed, whitespace-collapsed text content (capped). */
  text: string;
  attributes: Record<string, string>;
  rect: { x: number; y: number; width: number; height: number };
  /** URL of the frame the element lives in. */
  url: string;
}

/** A console error/warning captured from the preview. */
export interface LogEntry {
  level: "error" | "warn";
  message: string;
  ts: number;
}

/** A failed network request (status >= 400 or thrown) from the preview. */
export interface NetworkEntry {
  url: string;
  method: string;
  /** HTTP status, or 0 when the request threw (network error / CORS). */
  status: number;
  error?: string;
  ts: number;
}

/** Messages the dashboard page sends to the extension bridge. */
export type PickerPageMessage = {
  source: typeof PICKER_PAGE_SOURCE;
  type:
    | "ping"
    | "arm"
    | "disarm"
    | "collect-logs"
    | "collect-network"
    | "screenshot";
};

/** Messages the extension bridge sends back to the dashboard page. */
export type PickerExtMessage =
  | { source: typeof PICKER_EXT_SOURCE; type: "pong"; version: string }
  | { source: typeof PICKER_EXT_SOURCE; type: "armed" }
  | { source: typeof PICKER_EXT_SOURCE; type: "disarmed" }
  | {
      source: typeof PICKER_EXT_SOURCE;
      type: "selected";
      element: PickedElement;
    }
  | { source: typeof PICKER_EXT_SOURCE; type: "logs"; entries: LogEntry[] }
  | {
      source: typeof PICKER_EXT_SOURCE;
      type: "network";
      entries: NetworkEntry[];
    }
  | {
      source: typeof PICKER_EXT_SOURCE;
      type: "counts";
      logs: number;
      network: number;
    }
  | {
      source: typeof PICKER_EXT_SOURCE;
      type: "screenshot";
      dataUrl?: string;
      error?: string;
    };

/**
 * Short, chip-friendly label for a picked element, e.g. `<button#submit.btn>`.
 * Capped so a long class list doesn't blow out the composer chip.
 */
export function formatPickedElementLabel(el: PickedElement): string {
  const id = el.id ? `#${el.id}` : "";
  const cls = el.classes.length ? `.${el.classes[0]}` : "";
  return `<${el.tagName}${id}${cls}>`;
}

/**
 * Render a picked element as a chat-ready context block. Kept here (not in the
 * hook) so any surface can format selections identically.
 */
export function formatPickedElement(el: PickedElement): string {
  const lines: string[] = ["Selected element from the preview:"];
  const classes = el.classes.length ? `.${el.classes.join(".")}` : "";
  lines.push(`- Tag: \`<${el.tagName}${el.id ? `#${el.id}` : ""}${classes}>\``);
  lines.push(`- Selector: \`${el.selector}\``);
  if (el.text) lines.push(`- Text: "${el.text}"`);

  const interestingAttrs = Object.entries(el.attributes).filter(
    ([name]) => !["class", "id", "style"].includes(name),
  );
  if (interestingAttrs.length) {
    const rendered = interestingAttrs
      .slice(0, 8)
      .map(([k, v]) => `${k}="${v}"`)
      .join(" ");
    lines.push(`- Attributes: \`${rendered}\``);
  }
  lines.push(`- URL: ${el.url}`);
  return lines.join("\n");
}

/** Render captured console errors/warnings as a chat-ready block. */
export function formatLogs(entries: LogEntry[]): string {
  const body = entries
    .map((e) => `[${e.level}] ${e.message}`)
    .join("\n")
    .slice(0, 4000);
  return [
    `Console output from the preview (${entries.length} ${
      entries.length === 1 ? "entry" : "entries"
    }):`,
    "```",
    body,
    "```",
  ].join("\n");
}

/** Render failed network requests as a chat-ready block. */
export function formatNetwork(entries: NetworkEntry[]): string {
  const body = entries
    .map((e) => {
      const status = e.status === 0 ? `ERR ${e.error ?? "network error"}` : e.status;
      return `${e.method} ${e.url} → ${status}`;
    })
    .join("\n")
    .slice(0, 4000);
  return [
    `Failed requests in the preview (${entries.length} ${
      entries.length === 1 ? "request" : "requests"
    }):`,
    "```",
    body,
    "```",
  ].join("\n");
}
