/**
 * @fileType module
 * @domain picker
 * @pattern message-protocol
 * @ai-summary Shared message contract + types between the dashboard and the
 *   Kody Element Picker browser extension. Mirrors extension/src/content.js.
 */

/** `window.postMessage` discriminators. Mirrored in extension/src/content.js. */
export const PICKER_PAGE_SOURCE = "kody-picker:page";
export const PICKER_EXT_SOURCE = "kody-picker:ext";

/** Static download for the unpacked extension (regenerated by `pnpm picker:pack`). */
export const PICKER_DOWNLOAD_PATH = "/kody-element-picker.zip";
/** User-facing install/setup guide. */
export const PICKER_DOCS_URL =
  "https://github.com/aharonyaircohen/Kody-Dashboard/blob/main/docs/element-picker.md";
/** One-line install hint shown on download (full steps in PICKER_DOCS_URL). */
export const PICKER_INSTALL_HINT =
  "Picker downloading. Unzip it, open chrome://extensions, turn on Developer mode, click Load unpacked, pick the folder, then reload this tab.";

/** A DOM element the user clicked inside the preview iframe. */
export interface PickedElement {
  /** Best-effort CSS selector (id-anchored, else nth-of-type path). */
  selector: string;
  tagName: string;
  id: string | null;
  classes: string[];
  /** Trimmed, whitespace-collapsed text content (capped). */
  text: string;
  attributes: Record<string, string>;
  rect: { x: number; y: number; width: number; height: number };
  /** URL of the frame the element lives in. */
  url: string;
}

/** A console error/warning captured from the preview. */
export interface LogEntry {
  level: "error" | "warn";
  message: string;
  ts: number;
}

/** A failed network request (status >= 400 or thrown) from the preview. */
export interface NetworkEntry {
  url: string;
  method: string;
  /** HTTP status, or 0 when the request threw (network error / CORS). */
  status: number;
  error?: string;
  ts: number;
}

/** A single timed resource in a performance snapshot. */
export interface PerfResource {
  url: string;
  type: string;
  durationMs: number;
  bytes: number;
}

/** A performance snapshot of the preview (page load timings + resources). */
export interface PerfReport {
  url: string;
  ttfbMs: number;
  domContentLoadedMs: number;
  loadMs: number;
  fcpMs: number;
  lcpMs: number;
  resourceCount: number;
  totalBytes: number;
  slowest: PerfResource[];
}

/** A recorded user action, turned into a Playwright step. */
export interface RecordedStep {
  type: "click" | "fill";
  selector: string;
  text?: string;
  value?: string;
}

/** Messages the dashboard page sends to the extension bridge. */
export type PickerPageMessage = {
  source: typeof PICKER_PAGE_SOURCE;
  type:
    | "ping"
    | "arm"
    | "disarm"
    | "collect-logs"
    | "collect-network"
    | "collect-perf"
    | "record-start"
    | "record-stop"
    | "screenshot";
};

/** Messages the extension bridge sends back to the dashboard page. */
export type PickerExtMessage =
  | { source: typeof PICKER_EXT_SOURCE; type: "pong"; version: string }
  | { source: typeof PICKER_EXT_SOURCE; type: "armed" }
  | { source: typeof PICKER_EXT_SOURCE; type: "disarmed" }
  | {
      source: typeof PICKER_EXT_SOURCE;
      type: "selected";
      element: PickedElement;
    }
  | { source: typeof PICKER_EXT_SOURCE; type: "logs"; entries: LogEntry[] }
  | {
      source: typeof PICKER_EXT_SOURCE;
      type: "network";
      entries: NetworkEntry[];
    }
  | {
      source: typeof PICKER_EXT_SOURCE;
      type: "counts";
      logs: number;
      network: number;
    }
  | { source: typeof PICKER_EXT_SOURCE; type: "perf"; report: PerfReport }
  | {
      source: typeof PICKER_EXT_SOURCE;
      type: "recording";
      steps: RecordedStep[];
      url: string;
    }
  | { source: typeof PICKER_EXT_SOURCE; type: "rec-count"; count: number }
  | {
      source: typeof PICKER_EXT_SOURCE;
      type: "screenshot";
      dataUrl?: string;
      error?: string;
    };

/**
 * Short, chip-friendly label for a picked element, e.g. `<button#submit.btn>`.
 * Capped so a long class list doesn't blow out the composer chip.
 */
export function formatPickedElementLabel(el: PickedElement): string {
  const id = el.id ? `#${el.id}` : "";
  const cls = el.classes.length ? `.${el.classes[0]}` : "";
  return `<${el.tagName}${id}${cls}>`;
}

/**
 * Render a picked element as a chat-ready context block. Kept here (not in the
 * hook) so any surface can format selections identically.
 */
export function formatPickedElement(el: PickedElement): string {
  const lines: string[] = ["Selected element from the preview:"];
  const classes = el.classes.length ? `.${el.classes.join(".")}` : "";
  lines.push(`- Tag: \`<${el.tagName}${el.id ? `#${el.id}` : ""}${classes}>\``);
  lines.push(`- Selector: \`${el.selector}\``);
  if (el.text) lines.push(`- Text: "${el.text}"`);

  const interestingAttrs = Object.entries(el.attributes).filter(
    ([name]) => !["class", "id", "style"].includes(name),
  );
  if (interestingAttrs.length) {
    const rendered = interestingAttrs
      .slice(0, 8)
      .map(([k, v]) => `${k}="${v}"`)
      .join(" ");
    lines.push(`- Attributes: \`${rendered}\``);
  }
  lines.push(`- URL: ${el.url}`);
  return lines.join("\n");
}

/** Render captured console errors/warnings as a chat-ready block. */
export function formatLogs(entries: LogEntry[]): string {
  const body = entries
    .map((e) => `[${e.level}] ${e.message}`)
    .join("\n")
    .slice(0, 4000);
  return [
    `Console output from the preview (${entries.length} ${
      entries.length === 1 ? "entry" : "entries"
    }):`,
    "```",
    body,
    "```",
  ].join("\n");
}

function ms(n: number): string {
  return n >= 1000 ? `${(n / 1000).toFixed(2)}s` : `${Math.round(n)}ms`;
}
function kb(bytes: number): string {
  return bytes >= 1024 * 1024
    ? `${(bytes / 1024 / 1024).toFixed(1)}MB`
    : `${Math.round(bytes / 1024)}KB`;
}

/** Render a performance snapshot as a chat-ready, actionable block. */
export function formatPerf(report: PerfReport): string {
  const lines = [
    "Preview performance snapshot:",
    `- TTFB: ${ms(report.ttfbMs)}`,
    `- First Contentful Paint: ${ms(report.fcpMs)}`,
    `- Largest Contentful Paint: ${report.lcpMs ? ms(report.lcpMs) : "n/a"}`,
    `- DOMContentLoaded: ${ms(report.domContentLoadedMs)}`,
    `- Load: ${report.loadMs ? ms(report.loadMs) : "still loading"}`,
    `- Resources: ${report.resourceCount} (${kb(report.totalBytes)} transferred)`,
  ];
  if (report.slowest.length) {
    lines.push("- Slowest resources:");
    for (const r of report.slowest) {
      const file = r.url.split("/").pop() || r.url;
      lines.push(`  - ${ms(r.durationMs)} · ${kb(r.bytes)} · ${r.type} · ${file}`);
    }
  }
  lines.push(`- URL: ${report.url}`);
  return lines.join("\n");
}

/** Turn recorded actions into a Playwright test the user/Kody can save. */
export function formatPlaywrightTest(steps: RecordedStep[], url: string): string {
  const esc = (s: string) => s.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
  const body = [`  await page.goto('${esc(url)}');`];
  for (const step of steps) {
    if (step.type === "click") {
      const comment = step.text ? `  // ${step.text}` : "";
      body.push(`  await page.click('${esc(step.selector)}');${comment}`);
    } else {
      body.push(`  await page.fill('${esc(step.selector)}', '${esc(step.value ?? "")}');`);
    }
  }
  return [
    `Recorded ${steps.length} step(s) as a Playwright test:`,
    "```ts",
    `import { test, expect } from '@playwright/test';`,
    "",
    `test('recorded flow', async ({ page }) => {`,
    ...body,
    `  // TODO: add assertions for what should be true at the end.`,
    `});`,
    "```",
  ].join("\n");
}

/** Render failed network requests as a chat-ready block. */
export function formatNetwork(entries: NetworkEntry[]): string {
  const body = entries
    .map((e) => {
      const status = e.status === 0 ? `ERR ${e.error ?? "network error"}` : e.status;
      return `${e.method} ${e.url} → ${status}`;
    })
    .join("\n")
    .slice(0, 4000);
  return [
    `Failed requests in the preview (${entries.length} ${
      entries.length === 1 ? "request" : "requests"
    }):`,
    "```",
    body,
    "```",
  ].join("\n");
}
