/**
 * @fileoverview Unit tests for engine install — verifies kody.config.json creation
 * @testFramework vitest
 * @domain engine-install
 *
 * Tests that installEngine creates kody.config.json with the resolved default
 * model and default implementation.
 */

import { beforeEach, describe, expect, it, vi } from "vitest";

// Variables now live in Convex (repoDocs kind "variables") — mock the client.
const convex = vi.hoisted(() => ({
  query: vi.fn(),
  mutation: vi.fn(),
}));
const vault = vi.hoisted(() => ({
  read: vi.fn(),
}));
const webhooks = vi.hoisted(() => ({
  ensureWebhook: vi.fn(),
}));

vi.mock("convex/browser", () => ({
  ConvexHttpClient: class {
    query = convex.query;
    mutation = convex.mutation;
  },
}));
vi.mock("@kody-ade/base/vault/store", () => ({
  readVault: vault.read,
}));
vi.mock("@dashboard/lib/webhooks/register", () => webhooks);

import { _resetConvexClient } from "@kody-ade/base/backend/convex";
import { invalidateVariablesCache } from "@kody-ade/base/variables/store";
import {
  installEngine,
  WORKFLOW_TEMPLATE_SOURCE,
  type InstallEngineInput,
} from "@dashboard/lib/engine/install";

const KODY_WORKFLOW = `# Generated by @kody-ade/kody-engine.
name: kody
sessionId:
message:
dashboardUrl:
DASHBOARD_URL:
permissions:
  id-token: write
token: \${{ secrets.GH_PAT || secrets.KODY_TOKEN || github.token }}
run: npx -y -p @kody-ade/kody-engine@latest kody-engine
`;

/** Seed the Convex variables doc returned by repoDocs:get. */
function mockVariables(models: Array<Record<string, unknown>>) {
  convex.query.mockResolvedValue({
    doc: {
      version: 1,
      variables: {
        LLM_MODELS: {
          value: JSON.stringify(models),
          updatedAt: "2026-01-01T00:00:00.000Z",
        },
      },
    },
    updatedAt: "2026-01-01T00:00:00.000Z",
  });
}

beforeEach(() => {
  vi.clearAllMocks();
  _resetConvexClient();
  process.env.CONVEX_URL = "https://example.convex.cloud";
  invalidateVariablesCache("example", "my-repo");
  convex.query.mockResolvedValue(null); // no variables doc by default
  vault.read.mockResolvedValue({
    doc: { version: 1, secrets: {} },
    sha: null,
  });
  webhooks.ensureWebhook.mockResolvedValue({
    ok: true,
    created: false,
    hookId: 42,
  });
  vi.stubGlobal(
    "fetch",
    vi
      .fn()
      .mockResolvedValue(
        new Response(KODY_WORKFLOW, { status: 200, statusText: "OK" }),
      ),
  );
});

// ──────────────────────────────────────────────────────────────────────────────
// Mock helpers
// ──────────────────────────────────────────────────────────────────────────────

function createMockOctokit(overrides?: Record<string, unknown>) {
  const repos = {
    getContent: vi.fn().mockResolvedValue({
      data: { content: "", sha: "abc123" },
    }),
    createOrUpdateFileContents: vi.fn().mockResolvedValue({
      data: {
        commit: { sha: "commitsha" },
        content: {
          html_url:
            "https://github.com/example/repo/blob/main/.github/workflows/kody.yml",
        },
      },
    }),
  };

  return {
    repos,
    rest: {
      repos,
      actions: {
        getRepoPublicKey: vi.fn().mockResolvedValue({
          data: { key: "mock-public-key", key_id: "key-id-123" },
        }),
        createOrUpdateRepoSecret: vi.fn().mockResolvedValue({}),
      },
    },
    ...overrides,
  } as any;
}

/** Spy on every createOrUpdateFileContents call and capture the path + content. */
function captureFileWrites(octokit: ReturnType<typeof createMockOctokit>) {
  const calls: Array<{ path: string; content: string }> = [];
  vi.spyOn(octokit.rest.repos, "createOrUpdateFileContents").mockImplementation(
    async (params: any) => {
      calls.push({
        path: params.path,
        content: Buffer.from(params.content, "base64").toString("utf-8"),
      });
      return {
        data: {
          commit: { sha: "commitsha" },
          content: {
            html_url: `https://github.com/example/repo/blob/main/${params.path}`,
          },
        },
      };
    },
  );
  return {
    calls,
    getByPath: (path: string) => calls.findLast((c) => c.path === path),
  };
}

// ──────────────────────────────────────────────────────────────────────────────
// Tests
// ──────────────────────────────────────────────────────────────────────────────

describe("installEngine", () => {
  it("reports a skipped local webhook without failing the engine install", async () => {
    webhooks.ensureWebhook.mockResolvedValueOnce({
      ok: false,
      skipped: true,
      error: "public_url_required",
    });

    const result = await installEngine({
      octokit: createMockOctokit(),
      owner: "example",
      repo: "my-repo",
      token: "ghp_mocktoken",
      hookUrl: "http://localhost:3333/api/webhooks/github",
    });

    expect(result.ok).toBe(true);
    if (!result.ok) throw new Error(result.error);
    expect(result.webhook).toEqual({
      ok: false,
      skipped: true,
      error: "public_url_required",
    });
    expect(result.summary).toContain(
      "Webhook skipped — configure a public HTTPS dashboard URL.",
    );
  });

  it("preserves safe GitHub webhook failure context", async () => {
    webhooks.ensureWebhook.mockResolvedValueOnce({
      ok: false,
      error: "patch hook failed",
      status: 403,
      detail: "Resource not accessible by personal access token",
    });

    const result = await installEngine({
      octokit: createMockOctokit(),
      owner: "example",
      repo: "my-repo",
      token: "ghp_mocktoken",
      hookUrl: "https://dashboard.example.com/api/webhooks/github",
    });

    expect(result.ok).toBe(true);
    if (!result.ok) throw new Error(result.error);
    expect(result.webhook).toMatchObject({
      ok: false,
      error: "patch hook failed",
      status: 403,
      detail: "Resource not accessible by personal access token",
    });
    expect(result.summary).toContain(
      "Webhook FAILED — Resource not accessible by personal access token (HTTP 403).",
    );
  });

  it("keeps user vault secrets out of GitHub Actions", async () => {
    vault.read.mockResolvedValue({
      doc: {
        version: 1,
        secrets: {
          OPENAI_API_KEY: {
            value: "vault-only-value",
            updatedAt: "2026-01-01T00:00:00.000Z",
          },
        },
      },
      sha: null,
    });
    const octokit = createMockOctokit();

    const result = await installEngine({
      octokit,
      owner: "example",
      repo: "my-repo",
      token: "ghp_mocktoken",
      hookUrl: "https://dashboard.example.com/api/webhooks/github",
    });

    expect(result.ok).toBe(true);
    expect(octokit.rest.actions.getRepoPublicKey).toHaveBeenCalledTimes(1);
    expect(vault.read).not.toHaveBeenCalled();
    expect(result).not.toHaveProperty("vaultMirror");
  });

  describe("kody.config.json creation", () => {
    it("creates kody.config.json at the repo root after the workflow", async () => {
      const octokit = createMockOctokit();
      const { getByPath } = captureFileWrites(octokit);

      const input: InstallEngineInput = {
        octokit,
        owner: "example",
        repo: "my-repo",
        token: "ghp_mocktoken",
        hookUrl: "https://dashboard.example.com/api/webhooks/github",
      };

      const result = await installEngine(input);

      expect(result.ok).toBe(true);
      if (!result.ok) throw new Error(result.error);
      expect(result.workflow.templateSource).toBe(WORKFLOW_TEMPLATE_SOURCE);

      // kody.config.json must be created
      const configFile = getByPath("kody.config.json");
      expect(configFile).toBeDefined();
    });

    it("writes a kody.yml workflow that accepts dashboard chat inputs", async () => {
      const octokit = createMockOctokit();
      const { getByPath } = captureFileWrites(octokit);

      const input: InstallEngineInput = {
        octokit,
        owner: "example",
        repo: "my-repo",
        token: "ghp_mocktoken",
        hookUrl: "https://dashboard.example.com/api/webhooks/github",
      };

      await installEngine(input);

      const workflowFile = getByPath(".github/workflows/kody.yml");
      expect(workflowFile).toBeDefined();
      expect(workflowFile!.content).toContain("sessionId:");
      expect(workflowFile!.content).toContain("message:");
      expect(workflowFile!.content).toContain("dashboardUrl:");
      expect(workflowFile!.content).toContain("DASHBOARD_URL:");
      expect(workflowFile!.content).toContain("kody-engine");
      expect(workflowFile!.content).toContain("id-token: write");
      expect(workflowFile!.content).toContain(
        "secrets.GH_PAT || secrets.KODY_TOKEN || github.token",
      );
      expect(fetch).toHaveBeenCalledWith(WORKFLOW_TEMPLATE_SOURCE, {
        cache: "no-store",
      });
    });

    it("kody.config.json does not write a default implementation override", async () => {
      const octokit = createMockOctokit();
      const { getByPath } = captureFileWrites(octokit);

      const input: InstallEngineInput = {
        octokit,
        owner: "example",
        repo: "my-repo",
        token: "ghp_mocktoken",
        hookUrl: "https://dashboard.example.com/api/webhooks/github",
      };

      await installEngine(input);

      const configFile = getByPath("kody.config.json");
      expect(configFile).toBeDefined();
      const parsed = JSON.parse(configFile!.content);
      expect(parsed.defaultImplementation).toBeUndefined();
    });

    it("kody.config.json contains agent.model when variables.json exists with models", async () => {
      const octokit = createMockOctokit();
      const { getByPath } = captureFileWrites(octokit);

      // Simulate the variables doc returning a default model
      mockVariables([
        {
          id: "example/chat-model",
          label: "Example Chat Model",
          provider: "openai",
          protocol: "openai",
          baseURL: "",
          modelName: "chat-model",
          apiKeySecret: "MY_API_KEY",
          enabled: true,
          default: true,
        },
      ]);

      const input: InstallEngineInput = {
        octokit,
        owner: "example",
        repo: "my-repo",
        token: "ghp_mocktoken",
        hookUrl: "https://dashboard.example.com/api/webhooks/github",
      };

      await installEngine(input);

      const configFile = getByPath("kody.config.json");
      expect(configFile).toBeDefined();
      const parsed = JSON.parse(configFile!.content);
      // No engineDefault flag → falls back to the chat default. The entry id
      // is already in provider/model form, so it's used verbatim. Written to
      // `agent.model` (the key the engine reads), not the legacy model.default.
      expect(parsed.agent?.model).toBe("example/chat-model");
      expect(parsed.model).toBeUndefined();
    });

    it("prefers the engineDefault model over the chat default for agent.model", async () => {
      const octokit = createMockOctokit();
      const { getByPath } = captureFileWrites(octokit);

      mockVariables([
        {
          id: "anthropic/claude-sonnet-4-6",
          label: "Chat",
          provider: "anthropic",
          protocol: "anthropic",
          baseURL: "",
          modelName: "claude-sonnet-4-6",
          apiKeySecret: "ANTHROPIC_API_KEY",
          enabled: true,
          default: true,
        },
        {
          id: "minimax/MiniMax-M3",
          label: "Engine",
          provider: "custom",
          protocol: "openai",
          baseURL: "https://api.minimax.io/v1",
          modelName: "MiniMax-M3",
          apiKeySecret: "MINIMAX_API_KEY",
          enabled: true,
          engineDefault: true,
        },
      ]);

      const input: InstallEngineInput = {
        octokit,
        owner: "example",
        repo: "my-repo",
        token: "ghp_mocktoken",
        hookUrl: "https://dashboard.example.com/api/webhooks/github",
      };

      await installEngine(input);

      const parsed = JSON.parse(getByPath("kody.config.json")!.content);
      expect(parsed.agent?.model).toBe("minimax/MiniMax-M3");
    });

    it("uses the built-in OpenRouter model when variables.json does not exist", async () => {
      const octokit = createMockOctokit();
      const { getByPath } = captureFileWrites(octokit);

      // Simulate variables.json not existing (404)
      vi.spyOn(octokit.repos, "getContent").mockImplementation(
        async (params: any) => {
          if (params.path === "my-repo/variables.json") {
            const error = new Error("Not Found") as unknown as {
              status: number;
            };
            error.status = 404;
            throw error;
          }
          return { data: { content: "", sha: "abc123" } };
        },
      );

      const input: InstallEngineInput = {
        octokit,
        owner: "example",
        repo: "my-repo",
        token: "ghp_mocktoken",
        hookUrl: "https://dashboard.example.com/api/webhooks/github",
      };

      const result = await installEngine(input);

      expect(result.ok).toBe(true);

      // The same built-in model shown in Chat keeps a fresh Engine runnable.
      const configFile = getByPath("kody.config.json");
      expect(configFile).toBeDefined();
      const parsed = JSON.parse(configFile!.content);
      expect(parsed.defaultImplementation).toBeUndefined();
      expect(parsed.agent?.model).toBe("openrouter/free");
    });

    it("preserves the repository model when no configured model replaces it", async () => {
      const octokit = createMockOctokit();
      const { getByPath } = captureFileWrites(octokit);

      vi.spyOn(octokit.repos, "getContent").mockImplementation(
        async (params: any) => {
          if (params.path === "kody.config.json") {
            const existingConfig = JSON.stringify({
              github: { owner: "example", repo: "my-repo" },
              agent: {
                model: "openrouter/deepseek/deepseek-v4-flash-latest",
              },
            });
            return {
              data: {
                content: Buffer.from(existingConfig).toString("base64"),
                sha: "existing-sha",
              },
            };
          }
          return { data: { content: "", sha: "abc123" } };
        },
      );

      await installEngine({
        octokit,
        owner: "example",
        repo: "my-repo",
        token: "ghp_mocktoken",
        hookUrl: "https://dashboard.example.com/api/webhooks/github",
      });

      const parsed = JSON.parse(getByPath("kody.config.json")!.content);
      expect(parsed.agent?.model).toBe(
        "openrouter/deepseek/deepseek-v4-flash-latest",
      );
    });

    it("merges into an existing kody.config.json, preserving other fields and stripping the legacy model key", async () => {
      const octokit = createMockOctokit();
      const { getByPath } = captureFileWrites(octokit);

      // Simulate kody.config.json already existing
      vi.spyOn(octokit.repos, "getContent").mockImplementation(
        async (params: any) => {
          if (params.path === "kody.config.json") {
            const existingConfig = JSON.stringify({
              model: { default: "old/model" },
              defaultImplementation: "old-implementation",
              github: { owner: "example", repo: "my-repo" },
              quality: { typecheck: "tsc --noEmit" },
            });
            return {
              data: {
                content: Buffer.from(existingConfig).toString("base64"),
                sha: "existing-sha",
              },
            };
          }
          return { data: { content: "", sha: "abc123" } };
        },
      );

      const input: InstallEngineInput = {
        octokit,
        owner: "example",
        repo: "my-repo",
        token: "ghp_mocktoken",
        hookUrl: "https://dashboard.example.com/api/webhooks/github",
      };

      await installEngine(input);

      const configFile = getByPath("kody.config.json");
      expect(configFile).toBeDefined();
      const parsed = JSON.parse(configFile!.content);
      // Merge preserves hand-authored fields (defaultImplementation, quality) instead of
      // clobbering them, and drops the legacy top-level `model` key.
      expect(parsed.defaultImplementation).toBe("old-implementation");
      expect(parsed.quality?.typecheck).toBe("tsc --noEmit");
      expect(parsed.model).toBeUndefined();
    });
  });
});
