/**
 * @fileType component
 * @domain kody
 * @pattern prd-card
 * @ai-summary Preview card showing generated PRD in real-time
 */
"use client";

import type { Scenario } from "@dashboard/lib/scenario-schema-stub";
import { Badge } from "@dashboard/ui/badge";
import { Button } from "@dashboard/ui/button";
import { Label } from "@dashboard/ui/label";
import { Copy, Check } from "lucide-react";
import { useState } from "react";

interface PRDCardProps {
  scenario: Partial<Scenario>;
  expanded?: boolean;
}

export function PRDCard({ scenario, expanded = false }: PRDCardProps) {
  const [copied, setCopied] = useState(false);

  const generateMarkdown = () => {
    const lines: string[] = [];

    lines.push(`# PRD: ${scenario.name || "Untitled Scenario"}`);
    lines.push("");

    lines.push("## Overview");
    lines.push("");
    lines.push(
      `Implement ${scenario.name || "the scenario"} following the scenario-first development system.`,
    );
    lines.push("");

    if (scenario.type) {
      lines.push("## Type");
      lines.push("");
      lines.push(`**Category:** ${scenario.type}`);
      lines.push("");
    }

    if (scenario.steps && scenario.steps.length > 0) {
      lines.push("## Steps");
      lines.push("");
      lines.push("| Type | Action | Target | Component |");
      lines.push("|------|--------|--------|-----------|");
      for (const step of scenario.steps) {
        lines.push(
          `| ${step.type} | ${step.action} | ${step.target} | ${step.component || "-"} |`,
        );
      }
      lines.push("");
    }

    if (scenario.prototype) {
      lines.push("## Prototype");
      lines.push("");
      lines.push(`Reference: \`${scenario.prototype}\``);
      lines.push("");
    }

    lines.push("---");
    lines.push("");
    lines.push("*Generated by Scenario Editor*");

    return lines.join("\n");
  };

  const markdown = generateMarkdown();

  const handleCopy = async () => {
    await navigator.clipboard.writeText(markdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (expanded) {
    return (
      <div className="space-y-4">
        <div className="flex justify-end">
          <Button variant="outline" size="sm" onClick={handleCopy}>
            {copied ? (
              <>
                <Check className="h-4 w-4 mr-1" />
                Copied
              </>
            ) : (
              <>
                <Copy className="h-4 w-4 mr-1" />
                Copy Markdown
              </>
            )}
          </Button>
        </div>
        <pre className="whitespace-pre-wrap text-sm bg-muted p-4 rounded-lg overflow-x-auto">
          {markdown}
        </pre>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {/* Summary */}
      <div className="space-y-2">
        <div className="flex items-center gap-2">
          <Badge variant={scenario.type === "core" ? "default" : "secondary"}>
            {scenario.type || "draft"}
          </Badge>
          {scenario.status && (
            <Badge variant="outline">{scenario.status}</Badge>
          )}
        </div>

        <h3 className="font-medium">{scenario.name || "Untitled Scenario"}</h3>
      </div>

      {/* Steps Preview */}
      {scenario.steps && scenario.steps.length > 0 && (
        <div className="space-y-2">
          <Label className="text-xs text-muted-foreground">STEPS</Label>
          <div className="space-y-1">
            {scenario.steps.slice(0, 3).map((step, index) => (
              <div key={index} className="text-sm">
                <span className="text-muted-foreground">{step.type}: </span>
                <span>{step.action} </span>
                <span className="text-muted-foreground">{step.target}</span>
                {step.component && (
                  <Badge variant="outline" className="ml-1 text-xs">
                    {step.component}
                  </Badge>
                )}
              </div>
            ))}
            {scenario.steps.length > 3 && (
              <p className="text-xs text-muted-foreground">
                +{scenario.steps.length - 3} more steps
              </p>
            )}
          </div>
        </div>
      )}

      {/* Empty State */}
      {!scenario.steps?.length && (
        <p className="text-sm text-muted-foreground">
          Add steps to see the preview
        </p>
      )}
    </div>
  );
}
