/**
 * @fileType utility
 * @domain backend
 * @pattern convex-backend
 * @ai-summary Server-side Convex access shared by every package: cached
 *   ConvexHttpClient singleton from CONVEX_URL and the tenant-id convention
 *   ("owner/repo") every entity function is scoped by. Mirrors the
 *   dashboard's lib/backend/convex-backend.ts so package code never imports
 *   the host app.
 */
import { ConvexHttpClient } from "convex/browser";
import { api } from "@kody-ade/backend/api";
import { withEscapedKeys } from "@kody-ade/backend/client";

let client: ConvexHttpClient | null = null;

/**
 * Cached ConvexHttpClient built from CONVEX_URL. Throws when unset.
 * Wrapped with withEscapedKeys so reserved-prefix keys ($/_) inside open
 * payloads round-trip through Convex — callers always see original keys.
 */
export function getConvexClient(): ConvexHttpClient {
  if (client) return client;
  const url = process.env.CONVEX_URL;
  if (!url) {
    throw new Error(
      "CONVEX_URL is not configured — the Kody backend requires a Convex deployment URL",
    );
  }
  client = withEscapedKeys(new ConvexHttpClient(url));
  return client;
}

/** Exported for unit tests — clears the cached client. */
export function _resetConvexClient(): void {
  client = null;
}

/** Tenant scope for every Convex entity call. */
export function tenantIdFor(owner: string, repo: string): string {
  return `${owner}/${repo}`;
}

/** Typed function references generated by the Convex backend package. */
export const backendApi = api;
